# Generated by Django 4.2.7 on 2023-11-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Отсутствует', max_length=100)),
                ('intro', models.CharField(default='Отсутствует', max_length=300)),
                ('text', models.TextField(default='Отсутствует')),
            ],
        ),
    ]
