# Generated by Django 4.2.7 on 2023-11-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aktors',
            name='gmail',
        ),
        migrations.RemoveField(
            model_name='aktors',
            name='mesto',
        ),
        migrations.RemoveField(
            model_name='aktors',
            name='number',
        ),
        migrations.AddField(
            model_name='aktors',
            name='name',
            field=models.CharField(default='Отсутствует', max_length=100),
        ),
        migrations.AddField(
            model_name='aktors',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
