# Generated by Django 4.2.7 on 2023-11-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Отсутствует', max_length=100)),
                ('text', models.TextField(blank=True)),
                ('godnost', models.CharField(default='Отсутствует', max_length=10)),
                ('price', models.CharField(default='Отсутствует', max_length=10)),
                ('colvo', models.CharField(default='Отсутствует', max_length=10)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
