# Generated by Django 4.2.7 on 2023-11-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='colvo',
            field=models.IntegerField(default='Отсутствует', max_length=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(default='Отсутствует', max_length=10),
        ),
    ]
