# Generated by Django 4.2.7 on 2023-11-23 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_products_colvo_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='colvo',
            field=models.IntegerField(default='Отсутствует'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(default='Отсутствует'),
        ),
        migrations.CreateModel(
            name='AddedProds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.products')),
            ],
        ),
    ]
