# Generated by Django 4.2.7 on 2023-11-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_products_colvo_alter_products_price_addedprods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addedprods',
            name='text',
        ),
        migrations.AddField(
            model_name='addedprods',
            name='colvo',
            field=models.IntegerField(default=0),
        ),
    ]
