# Generated by Django 4.2.7 on 2023-11-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_remove_addedprods_text_addedprods_colvo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(default='Отсутствует', max_length=110),
        ),
    ]
